services:
  frontend:
    build:
      context: ./frontend
    container_name: 50-50-frontend
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: 50-50-backend
    restart: always
    expose:
      - "4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
